#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

# chkconfig:   - 85 15
# description:  redis
# processname: redis

# Source function library.
. /etc/rc.d/init.d/functions

PORT=<port>
USER=<user>
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=<pid>
CONF=<conf>
OPT=<opt>
#"--sentinel"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting $EXEC $OPT ..."
                daemon --user $USER $EXEC $CONF $OPT
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                daemon --user $USER $CLIEXEC -p $PORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for $EXEC $OPT to shutdown ..."
                    sleep 1
                done
                echo "$EXEC $OPT stopped"
				rm -rf $PIDFILE
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
